### ISSUE TITLE
Implementation guide

### ISSUE THREAD

**Issue by mortiz85** [jkooten/pnm#1]
Hello jkooten thanks a lot for your contribution!

I wanted to implement PNM in my lab but unfortunately i'm lack of knowledge how to implement I see the code of yours can be useful and If possible I will contribute with it as well, but, could you guide me how to implement? first time? 

thanks in advance.

**Comment by jkooten** [comment]
Hi mortiz85, assuming you have cmts, cm, tftpserver and perl available and installed correctly. The decoders are in perl programming language. There are some dependencies so you need to make sure that these are installed on your system. dependencies are in the readme file of the decoders. The decoders mainly decode the PNM files and create a graph to view. The actual PNM measurement needs to be initiated on the devices via some snmpset commands.

for ofdmdsrxmer you would need to set the following oids:

$commstring == snmp community string
$modemip == modem ip address

snmpset -v2c -c $commstring $modemip 1.3.6.1.4.1.4491.2.1.27.1.1.1.1.0 i 1  ## SETS MEASUREMENT TO IPv4
snmpset -v2c -c $commstring $modemip 1.3.6.1.4.1.4491.2.1.27.1.1.1.2.0 d $pnmsrvr ## $pnmsrvr is the tftp server address
snmpset -v2c -c $commstring $modemip 1.3.6.1.4.1.4491.2.1.27.1.1.1.3.0 s $pnmsrvrroot ## pnm server root where pnm file will be placed

## SNMPSET PNMDsRxMer
snmpset -v2c -c $commstring $modemip 1.3.6.1.4.1.4491.2.1.27.1.2.5.1.8.0 s $pnmfilename ## filename of your pnm file
snmpset -v2c -c $commstring $modemip 1.3.6.1.4.1.4491.2.1.27.1.2.5.1.1.0 i 1 ## This will initite the PNM measurement

doing this correctly will result in a PNM file on the tftp onm server whoch you can decode with the decoder

**Comment by jkooten** [comment]
maybe it is best to first start with creating a PNM file like described above. after that you can focus on the decoders

**Comment by mortiz85** [comment]
Great!! I will give it a Try, appreciate it!
